# Generated by Django 4.1.1 on 2022-11-10 14:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "djangoproject",
            "0006_rename_t00_dayprices_h00_rename_t01_dayprices_h01_and_more",
        ),
    ]

    operations = [
        migrations.RenameField(
            model_name="dayprices",
            old_name="Hate",
            new_name="Time",
        ),
    ]
